cask "firefox"
cask "1password"
cask "alfred"
cask "rectangle"
cask "calibre"
cask "iterm2"
cask "meetingbar"
cask "steam"
cask "bartender"

cask "signal"
cask "slack"
cask "readdle-spark"

cask "visual-studio-code"
cask "webstorm"
cask "pycharm-ce"
cask "postman"
cask "docker"
cask "tailscale"
